export const usersData = [
  {
    id: 1,
    name: "Firuz",
    lastName: "Azizbekov",
    gender: "male",
    email: "john.doe@example.com",
  },
  {
    id: 2,
    name: "Asel",
    lastName: "Eje",
    gender: "female",
    email: "jane.doe@example.com",
  },
  {
    id: 3,
    name: "Aruuke",
    lastName: "Sanjarbekovna",
    gender: "male",
    email: "bob.smith@example.com",
  },
  {
    id: 4,
    name: "Dastan",
    lastName: "Akatov",
    gender: "female",
    email: "bob.smith@example.com",
  },
  {
    id: 5,
    name: "Saadat",
    lastName: "Orozova",
    gender: "female",
    email: "bob.smith@example.com",
  },
  {
    id: 6,
    name: "Erik",
    lastName: "Stybaev",
    gender: "male",
    email: "bob.smith@example.com",
  },
  {
    id: 7,
    name: "Alisher",
    lastName: "Isaev",
    gender: "male",
    email: "bob.smith@example.com",
  },
  {
    id: 8,
    name: "Islam",
    lastName: "Momukeev",
    gender: "male",
    email: "bob.smith@example.com",
  },
  {
    id: 9,
    name: "Ayana",
    lastName: "Supueva",
    gender: "male",
    email: "bob.smith@example.com",
  },
];
